std = "lua51"
max_line_length = false

exclude_files = {
    ".luacheckrc"
}

-- see https://luacheck.readthedocs.io/en/stable/warnings.html#list-of-warnings
-- and https://luacheck.readthedocs.io/en/stable/cli.html#patterns
ignore = {
    "11./SLASH_.*", -- Accessing an undefined (Slash) global variable
    "211", -- Unused local variable
    "212", -- Unused argument (e.g. "self")
    "213", -- Unused loop variable
    "432", -- Shadowing upvalue argument (e.g. "self")
}

read_globals = {
    "hooksecurefunc",

    -- Third party libraries
    "LibStub",

    -- Addons
    "CompactRaidFrameManager_SetSetting",
    "CUSTOM_CLASS_COLORS",
    "OmniCD",

    -- Cell constants
    "CELL_BORDER_COLOR",
    "CELL_BORDER_SIZE",
    "CELL_FADE_OUT_HEALTH_PERCENT",
    "CELL_NICKTAG_ENABLED",
    "CELL_TOOLTIP_REMOVE_RAID_SETUP_DETAILS",
    "CELL_USE_LIBHEALCOMM",
    "CELL_RECTANGULAR_CUSTOM_INDICATOR_ICONS",
    "CELL_SUMMON_ICONS_ENABLED",
    "CELL_SHOW_RAID_PET_OWNER_NAME",

    -- Cell API
    "Cell_DevExpansionNames",
    "Cell_ExpansionData",
    "Cell_OnAddonCompartmentClick",
    "Cell",
    "CellAnchorFrame",
    "CellBuffTrackerFrame",
    "CellCharacterDB",
    "CellDB",
    "CellDropdownList",
    "CellGlowsPreviewButton",
    "CellIndicatorsPreviewButton",
    "CellLayoutsPreviewButton",
    "CellLoadingBar",
    "CellMainFrame",
    "CellMenuFrame",
    "CellNPCFrameAnchor",
    "CellOptionsFrame",
    "CellPartyFrameHeader",
    "CellPartyFrameHeaderUnitButton1",
    "CellPartyFrameHeaderUnitButton1Pet",
    "CellQuickAssist_OnLoad",
    "CellQuickAssistAnchorFrame",
    "CellQuickAssistFrame",
    "CellRaidDebuffsPreviewButton",
    "CellRaidPetAnchorFrame",
    "CellSoloFramePet",
    "CellSoloFramePlayer",
    "CellSpellTooltip",
    "CellTooltip",
    "RaidDebuffs_HideGlow",
    "CheckConflicts",

    -- Blizzard Data
    "WOW_PROJECT_CATACLYSM_CLASSIC",
    "WOW_PROJECT_CLASSIC",
    "WOW_PROJECT_ID",
    "WOW_PROJECT_MAINLINE",
    "WOW_PROJECT_WRATH_CLASSIC",

    -- Global constants
    "AUTO_SELF_CAST_KEY_TEXT",

    -- Lua APIs
    "abs",
    "ceil",
    "strsub",
    "floor",
    "format",
    "gsub",
    "max",
    "min",
    "mod",
    "random",
    "sort",
    "sqrt",
    "strfind",
    "string.split",
    "string.utf8len",
    "string.utf8sub",
    "strlen",
    "strlower",
    "strmatch",
    "strsplit",
    "strsplit",
    "strtrim",
    "strupper",
    "time",
    "tinsert",
    "tremove",
    "wipe",

    -- Global API
    "CanInspect",
    "ChatEdit_ActivateChat",
    "ChatEdit_ChooseBoxForSend",
    "CheckInteractDistance",
    "CreateBaseTooltipInfo",
    "CreateColor",
    "CreateFont",
    "CreateFrame",
    "CreateVector2D",
    "DemoteAssistant",
    "DoReadyCheck",
    "EJ_ContentTab_Select",
    "EJ_GetCreatureInfo",
    "EJ_GetCurrentTier",
    "EJ_GetEncounterInfoByIndex",
    "EJ_GetInstanceByIndex",
    "EJ_GetNumTiers",
    "EJ_GetTierInfo",
    "EJ_IsValidInstanceDifficulty",
    "EJ_SelectInstance",
    "EJ_SelectTier",
    "EJ_SetDifficulty",
    "FillLocalizedClassList",
    "GetActiveTalentGroup",
    "GetAddOnMemoryUsage",
    "GetAddOnMetadata",
    "GetBattlegroundInfo",
    "GetClassInfo",
    "GetCurrentBindingSet",
    "GetCursorPosition",
    "GetCVarBool",
    "GetInspectSpecialization",
    "GetInstanceInfo",
    "GetModifiedClick",
    "GetMouseFocus",
    "GetNormalizedRealmName",
    "GetNumBattlegroundTypes",
    "GetNumClasses",
    "GetNumGroupMembers",
    "GetNumSpecializationsForClassID",
    "GetNumSpellTabs",
    "GetNumTalentTabs",
    "GetPartyAssignment",
    "GetPhysicalScreenSize",
    "GetPrimaryTalentTree",
    "GetRaidRosterInfo",
    "GetRaidTargetIndex",
    "GetRaidTargetIndex",
    "GetReadyCheckStatus",
    "GetRealmName",
    "GetRealZoneText",
    "GetSpecialization",
    "GetSpecializationInfo",
    "GetSpecializationInfoByID",
    "GetSpecializationInfoForClassID",
    "GetSpecializationInfoForSpecID",
    "GetSpellBookItemName",
    "GetSpellCharges",
    "GetSpellCooldown",
    "GetSpellInfo",
    "GetSpellLink",
    "GetSpellTabInfo",
    "GetSpellTexture",
    "GetTalentInfo",
    "GetTalentTabInfo",
    "GetTexCoordsForRole",
    "GetTexCoordsForRoleSmallCircle",
    "GetThreatStatusColor",
    "GetTime",
    "GetUnitName",
    "InCombatLockdown",
    "InitiateRolePoll",
    "IsAltKeyDown",
    "IsControlKeyDown",
    "IsEncounterInProgress",
    "IsEveryoneAssistant",
    "IsFalling",
    "IsInGroup",
    "IsInGuild",
    "IsInInstance",
    "IsInRaid",
    "IsItemInRange",
    "IsLeftAltKeyDown",
    "IsLeftControlKeyDown",
    "IsRaidMarkerActive",
    "IsShiftKeyDown",
    "IsSpellInRange",
    "IsSpellKnown",
    "LE_PARTY_CATEGORY_INSTANCE",
    "NotifyInspect",
    "PlaySound",
    "PowerBarColor",
    "PromoteToAssistant",
    "RegisterStateDriver",
    "RegisterUnitWatch",
    "ReloadUI",
    "SecureHandlerSetFrameRef",
    "SendChatMessage",
    "SetCVar",
    "SetEveryoneIsAssistant",
    "SetRaidTarget",
    "SetRaidTargetIconTexture",
    "SwapRaidSubgroup",
    "UninviteUnit",
    "UnitAffectingCombat",
    "UnitAttackSpeed",
    "UnitAuraSlots",
    "UnitBuff",
    "UnitCanAssist",
    "UnitCanAttack",
    "UnitCanCooperate",
    "UnitCastingInfo",
    "UnitChannelInfo",
    "UnitClass",
    "UnitClassBase",
    "UnitDebuff",
    "UnitDetailedThreatSituation",
    "UnitExists",
    "UnitFactionGroup",
    "UnitFullName",
    "UnitGetIncomingHeals",
    "UnitGetTotalAbsorbs",
    "UnitGetTotalHealAbsorbs",
    "UnitGroupRolesAssigned",
    "UnitGUID",
    "UnitHasIncomingResurrection",
    "UnitHasVehicleUI",
    "UnitHealth",
    "UnitHealthMax",
    "UnitInOtherParty",
    "UnitInParty",
    "UnitInPartyIsAI",
    "UnitInPhase",
    "UnitInRaid",
    "UnitInRange",
    "UnitIsAFK",
    "UnitIsCharmed",
    "UnitIsConnected",
    "UnitIsDead",
    "UnitIsDeadOrGhost",
    "UnitIsDeadOrGhost",
    "UnitIsEnemy",
    "UnitIsFeignDeath",
    "UnitIsGhost",
    "UnitIsGroupAssistant",
    "UnitIsGroupLeader",
    "UnitIsOtherPlayersPet",
    "UnitIsPlayer",
    "UnitIsPlayer",
    "UnitIsPVP",
    "UnitIsSameServer",
    "UnitIsUnit",
    "UnitIsVisible",
    "UnitLevel",
    "UnitName",
    "UnitNameUnmodified",
    "UnitPhaseReason",
    "UnitPlayerOrPetInParty",
    "UnitPlayerOrPetInRaid",
    "UnitPower",
    "UnitPowerMax",
    "UnitPowerType",
    "UnitRace",
    "UnitSex",
    "UnitThreatSituation",
    "UnitVehicleSeatCount",
    "UnitVehicleSeatInfo",
    "UnregisterUnitWatch",
    "UpdateAddOnMemoryUsage",
    "WrapTextInColorCode",


    --

    "C_AddOns",
    "C_IncomingSummon",
    "C_Map",
    "C_NamePlate",
    "C_Timer",
    "C_TooltipInfo",
    "C_UnitAuras",
    "C_ClassTalents",
    "C_Traits",

    -- GlobalStrings.lua
    "ACTION_UNIT_DIED",

    -- Actions_Bar constants
    "BOOKTYPE_SPELL",

    -- Fonts_Frame constants
    "LOCALE_deDE",
    "LOCALE_frFR",
    "LOCALE_koKR",
    "LOCALE_zhCN",
    "LOCALE_zhTW",

    -- FrameXML globals
    "RAID_CLASS_COLORS",
    "UNIT_NAME_FONT_CHINESE",
    "UNIT_NAME_FONT_KOREAN",
    "ChatFontNormal",

    -- FrameXML functions
    "AuraUtil",
    "ChatFrame_AddMessageEventFilter",
    "CombatLogGetCurrentEventInfo",
    "DebuffTypeColor",
    "Enum",
    "GameFontNormal",
    "GameTooltip_SetDefaultAnchor",
    "GameTooltip",
    "GetClassColor",
    "MapUtil",
    "PingableType_UnitFrameMixin",
    "PixelUtil",
    "RegisterAttributeDriver",
    "SlashCmdList",
    "SmoothStatusBarMixin",
    "UIParent",
    "UISpecialFrames",
    "UnregisterAttributeDriver",
    "UnregisterStateDriver",
    "CreateObjectPool",
    "Round",

    -- SharedXML constants
    "SOUNDKIT",

    -- SharedXML functions
    "Mixin",
    "TooltipUtil",
    "Settings",
    "SettingsPanel",
}
